import { z } from "zod";
import mongoose from 'mongoose';

// Custom validation for MongoDB ObjectId strings
const objectIdSchema = z.string().refine(
  (val) => mongoose.Types.ObjectId.isValid(val),
  {
    message: "Invalid ObjectId format",
  }
);

export const variantSchema = z.object({
  size: z.string().min(1, "Size is required."),
  color: z.string().min(1, "Color is required."),
  price: z.number().min(0, "Price cannot be negative."),
  stock: z.number().int().min(0, "Stock cannot be negative."),
  _id: objectIdSchema.optional(), // _id is generated by MongoDB, optional for creation
});

export const createProductSchema = z.object({
  name: z.string().min(3, "Product name is required and must be at least 3 characters."),
  description: z.string().min(10, "Product description is required and must be at least 10 characters."),
  category: z.string().min(1, "Category is required."),
  imageUrls: z.array(z.string().url("Must be a valid URL.")).min(1, "At least one image URL is required."),
  isFeatured: z.boolean().default(false),
  variants: z.array(variantSchema).min(1, "At least one variant is required."),
}).strict();

export const updateProductSchema = z.object({
  name: z.string().min(3, "Product name must be at least 3 characters.").optional(),
  description: z.string().min(10, "Product description must be at least 10 characters.").optional(),
  category: z.string().min(1, "Category is required.").optional(),
  imageUrls: z.array(z.string().url("Must be a valid URL.")).min(1, "At least one image URL is required.").optional(),
  isFeatured: z.boolean().optional(),
  variants: z.array(variantSchema).min(1, "At least one variant is required.").optional(),
}).strict().partial(); // Allow partial updates